### ISSUE TITLE
USGS-Water sprint goals

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/EDR-API-Sprint#1]
## Narrative
At USGS-Water, our primary initial focus for EDR is a simple access API for our observational "site-based" data. Our use-cases are not limited to this, accessing data by pre-defined or custom (watershed) polygon or along a defined line (transect) are of interest, but secondary given our current development on waterdata.usgs.gov and waterservices.usgs.gov. Given this, we want to focus our efforts around the API and payload design of the `items` end point of EDR. Our interests are closely aligned with the work in: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/12

## Questions
- What would USGS site-metadata look like as a collection of EDR items?
- USGS has "collections" that are ad-hoc monitoring "networks", how does that fit with EDR?
- Our data have both "parameter codes" and "statistic codes" -- how does that intersect with EDR metadata and access? 
- Our sites are ostensibly associated to other features (rivers, lakes, etc.), how would we express those linkages within or on-top-of EDR?
- Our data services support a number of encodings, how do those get advertised and what is the EDR default? 

## Goals
- Mock up EDR collection metadata
- Mock up EDR item metadata
- Sequence diagrams with example request URLs / response hypertext
- Mock up EDR-default time series for an observation result at one of our sites.

## Participants
- @dblodgett-usgs 
- @jkreft-usgs
Shawna Gregory
Greg Petrochenkov

**Comment by chris-little** [comment]
@dblodgett-usgs About ".. both "parameter codes" and "statistic codes" -- " is a pattern we've encountered many times in GRIB, BUFR, CF-NetCDF and other parameter lists. I recommend in the shorter term to just use commonly used "statistic codes" exactly like parameter codes (e.g. 'mean temperature', 'standard deviation of temperature', etc). Trying to construct a  language to enable some generality of stats to be built from an atomic list of parameters is too hard at present.

**Comment by dblodgett-usgs** [comment]
I agree -- we usually concatenate them but some people _really_ want to split them out.

**Comment by sgby** [comment]
We discussed to use LINESTRING(), LINESTRINGZ(), LINESTRINGM(), LINESTRINGMZ() in crs to distinguish trajectory query pattern, for example:
+ A 2D trajectory, on the surface of earth, at the same time:
coords=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)

+ A 3D trajectory, on the surface of the earth but over a time range:
coords=LINESTRINGM(51.14 -2.98 1560507000, 51.36 -2.87 1560507600, 51.03 -3.15 1560508200, 50.74 -3.48 1560508500, 50.9 -3.36 1560510240)

+ A 3D trajectory, through a 3D volume with height or depth, for the same time:
coords=LINESTRINGZ(51.14 -2.98 0.1, 51.36 -2.87 0.2, 51.03 -3.15 0.3, 50.74 -3.48 0.4, 50.9 -3.36 0.5)

+ A 4D trajectory, through a 3D volume but over a time range:
coords=LINESTRINGZM(51.14 -2.98 0.1 1560507000,51.36 -2.87 0.2 1560507600, 51.03 -3.15 0.3 1560508200, 50.74 -3.48 0.4 1560508500, 50.9 -3.36 0.5 1560510240)

An example for querying rainfall data with a typhoon trajectory:
- Request: 
```
geos.whu.edu.cn/edr/collections/hainan_weather/trajectory?parametername=rainfall&coords=LINESTRINGM(112.7 21.1 1471392000, 112.5 20.9 1471402800, 112.6 20.5 1471413600, 112.7 20.6 1471424400, 112.7 20.7 1471435200)
```
- Response:
```
{
    "type": "Coverage",
    "domain": {
        "type": "Domain",
        "domainType": "Trajectory",
        "composite": {
            "dataType": "tuple",
            "coordinates": ["t", "x", "y"],
            "values": [ ["2016-08-17T08:00:00Z", 112.7, 21.1], ["2016-08-17T11:00:00Z", 112.5, 20.9], ["2016-08-17T14:00:00Z", 112.6, 20.5], ["2016-08-17T17:00:00Z", 112.7, 20.6],["2016-08-17T20:00:00Z", 112.7, 20.7]]
        }
    },
    "parameters": {
        "rainfall": {
            "type": "Parameter",
            "id": "rainfall",
            "description": {
                "en": "Rainfall value"
            },
            "unit": {
                "label": {
                    "en": "Mmmillimetre"
                },
                "symbol": {
                    "value": "mm"
                }
            },
            "observedProperty": {
                "id": "http://vocab.nerc.ac.uk/standard_name/rainfall/",
                "label": {
                    "en": "Rainfall"
                }
            }
        }
    },
    "ranges": {
        "rainfall": {
            "type": "NdArray",
            "dataType": "float",
            "axisNames": ["composite"],
            "shape": [5],
            "values": [12.2, 12, 13.3, 11.2, 8.7]
        }
    }
}
```

**Comment by chris-little** [comment]
We agreed on parameter list approach.
Sprint finished. 
Any other objectives and issues now on [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
