### ISSUE TITLE
Objective: Corridor, 3D or 4D

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#10]
Retrieve data from various data stores throughout a specified 'corridor' (i.e. a 'fat trajectory').

A 4D corridor, through a 3D volume but over a time range
( (x1,y1,z1,t1), (x2,y2,z2,t2), ...(xn,yn,zn,tn) ) plus r,z ranges.
This is the primary goal, driven by various use case, such as an aviation flight path. Other cases below are not so convincing,

A 3D corridor on the surface of the earth but over a time range. ( (x1,y1,t1), (x2,y2,t2), ...(xn,yn,tn) ) plus r range. This maybe needed for the Wuhan University objective., with a use case of a trajectory path and area of influence from a typhoon/hurricane forecast.

A 2D corridor on the surface of earth, at the same time. ( (x1,y1), (x2,y2), ...(xn,yn) ) plus r range. This is just a specialised 2D polygon, with a different specification of the boundary

A 3D trajectory, through a 3D volume with height or depth, for the same time
( (x1,y1,z1), (x2,y2,z2), ...(xn,yn,zn) ) plus r,z ranges. This is just a specialised 3D polygon, with a different specification of the boundary

**Comment by cmheazel** [comment]
@chris-little A 3D corridor on the surface of the earth but over a time range. Answer: What is the coverage of an airborne electro-optical collector. Applicable to motion imagery and stereo collections.

**Comment by chris-little** [comment]
@cmheazel I would say electro-optical sensing from an air or space borne instrument is a 4D corridor, but extending down to the surface of the earth, rather than just a fixed (?) distance from a trajectory linestring. Need to think about strereo-pairs aspect though. I propose we tackle this useful use case later.
Meteorological air and space borne sensors, such as in infrared or microwave bands, recognise that there is a depth of atmosphere which is emitting or transmitting radience, not just a discrete surface.
If the bulk of the radiance comes from the earth's surface, it could be considered a 3D trajectory (2D + Time)

**Comment by chris-little** [comment]
Issue postponed for future wowrk. No implementation or documented use case yet.
