### ISSUE TITLE
Groups versus Collections

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#11]
At the recent OGC Tech Committee in Ottawa, it seemed Collections of collections will be a valid pattern for the OGC APIs in general, and possibly for OGC API - Common specifically.

Can we replace Groups with collections without loss of generality?

**Comment by cmheazel** [comment]
@chris-little I'm a little reluctant to go down that path.  According to the General Feature Model, a Feature Collection is a collection of Features and Feature Collections.  A collections of collections path could rapidly become a very large and deep tree. Not something I would want to capture in an OpenAPI document. Perhaps we could use hypermedia navigation.  Follow the links to the node you want starting from /collections/{collectionId}.  Once you have the Feature (or Feature Collection) you want, you can access it directly using /items/{itemId}.

**Comment by cportele** [comment]
> According to the General Feature Model, a Feature Collection is a collection of Features and Feature Collections.

The General Feature Model does not include feature collections. @cmheazel - you must be referring to some other model?

**Comment by cmheazel** [comment]
@cportele You're right.  Don't know what I was thinking of.

**Comment by chris-little** [comment]
@m-burgoyne @cportele @cmheazel So, in the current EDR API documents, where we have specified 'group' in the path, can we call it a collection or not?
I suspect there is some significant work in delineating what EDR API collections and groups are and are not.

**Comment by m-burgoyne** [comment]
@chris-little I was awaiting the outcome of the collection of collections discussion.  I think it would become superfluous if collection of collections becomes an approved approach.

**Comment by chris-little** [comment]
Current ststus of wider OGC Collection discussion is that Collections are:
1. Separate conformance class in OGC API - Common: Part 1 Core.
2. Now proposed as a separate Part of the standard OGC API - Common: Part 2 Collections.
Transferred as an issue in [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
