### ISSUE TITLE
Items view of EDR resources.

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/EDR-API-Sprint#12]
The current spec leaves off here: http://docs.opengeospatial.org/DRAFTS/19-086.html#_items with:

> This example does have a flaw in that the EDR API provides no mechanism for the user to discover the available icao id’s in the metadata (the id’s are available in the query results but not in any of the available metadata outputs).

I want to look at what the JSON-Schema is for these items. 

This is working on the last three check boxes here: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/12#issuecomment-588001118

Will create a folder in the readme to contribute to.

**Comment by dblodgett-usgs** [comment]
See https://m-burgoyne.github.io/edr_optional_instance_api.html for current openAPI draft for /collections/{collectionID}/items/{itemID} path. (note there is a typo there "item" should be "items").

**Comment by cportele** [comment]
@dblodgett-usgs - I will try to monitor this issue as good as I can, not sure how much I can spend on this.

One comment after looking at the text in the document:

> `collections/metar/raw/items?id=KIAD&parametername=icao_id&time=2020-01-31T00:00:00Z/2020-02-01T04:00:00Z`
>
> This example does have a flaw in that the EDR API provides no mechanism for the user to discover the available icao id’s in the metadata (the id’s are available in the query results but not in any of the available metadata outputs).

If the idea is to be consistent with Features, I would have expected that `collections/metar/raw/items` returns the list of items (paged, if there are many) and that the query would look like `collections/metar/raw/items/KIAD?parametername=icao_id&datetime=2020-01-31T00:00:00Z/2020-02-01T04:00:00Z`.

I see that the OpenAPI definition seems to be at least close to that (unlike the text in the document).

**Comment by dblodgett-usgs** [comment]
Cool -- that's right in line with my thinking.

**Comment by chris-little** [comment]
@cportele As you have spotted - documentation (informative) is some way behind implementation (nearly normative).

**Comment by dblodgett-usgs** [comment]
Learning some of the tech on the job here -- so bear with me. 

I'm thinking something along the lines of this:

```json
{
  "type": "FeatureCollection",
  "crs": {
    "type": "EPSG",
    "properties": {
      "code": 4326,
      "coordinate_order": [ 1, 0 ]
    }
  },
  "features": [
    {
      "type": "Feature",
      "id": "123",
      "geometry": {
        "type": "Point",
        "coordinates": [ -105.683442, 36.740017 ]
      },
      "properties": {
        "datetime": "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z",
        "parametername": [ "param object 1", "param object 2" ],
        "label": "Something like a site name to use on a link",
        "uri": "https://feature_identifier"
      }
    }
  ]
}
```
This validates against the geojson schema anyways.

- `id` is what goes in `/collection/{collectionID}/items/{itemID}`. (I ripped this from OGC-API Features Example 12)
- `datetime` follows features.
- `parametername` follows the draft spec naming convention. (Does geojson really support arrays in the properties?!?)
- `label` because you have to have a list/link label in your app.
- `uri` which I was going to make `@id` to allude to json-ld and the idea that it should really be a linked data feature ID that 303 redirects if this is a real-world sampling feature. 

I'm not versed enough to sneak these extensions in to the geojson FeatureCollection schema. Maybe someone else can tackle that if this is a reasonable approach here?

Cool! `R` `sf` which wraps `gdal` says: (woot woot to even getting the datetime right and parameters as a list!!)
```r
> sf::read_sf("~/Documents/active_code/EDR-API-Sprint/items/test.geojson")
Simple feature collection with 1 feature and 5 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -105.6834 ymin: 36.74002 xmax: -105.6834 ymax: 36.74002
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
# A tibble: 1 x 6
  id    datetime            label                uri           parametername                geometry
  <chr> <dttm>              <chr>                <chr>         <list>                    <POINT [°]>
1 123   2018-02-11 18:00:00 Something like a si… https://feat… <chr [2]>        (-105.6834 36.74002)
```

**Comment by jkreft-usgs** [comment]
I'm pretty sure that you can do whatever you want in the properties of geoJSON.

**Comment by dblodgett-usgs** [comment]
Yes -- we can. The idea is to have something that is valid geoJSON but also adhering to a more specific EDR JSON schema that we can validate.

**Comment by jkreft-usgs** [comment]
OK, so i'm working on something here, with Dave doing a lot of the heavy lifting
https://jkreft-usgs.github.io/edr_site_based/

See #15 for more.
