### ISSUE TITLE
Further Development of Aggregation of Collections

### ISSUE THREAD

**Issue by ShaneMill1** [opengeospatial/EDR-API-Sprint#14]
Beginning Status:

Currently, the NWS has an implementation of the aggregation of collections for the use case of NAM and GFS grib data:

- This implementation is available here: [https://data-api.mdl.nws.noaa.gov/EDR-API/groups/US_Models?outputFormat=application%2Fjson](url)

What we want to accomplish:

- The aggregation of other data sources, such as grib data sources from other met offices, or other file types such as HDF5, netcdf, etc.

Below is a repository that we can start from that contains only the aggregation of NAM and GFS:

- [https://github.com/ShaneMill1/edr-automation](url)

**Comment by ShaneMill1** [comment]
Action Items:

Documentation of best practices

- We want to be able to document the approach for the naming convention, the workflow, etc.

Additional Data Ingest:
Test all of the resolutions laid out in nomads for GFS, NAM, RAP, HRRR, SREF?, RTMA?

- GFS
Resolutions
   0.25 - needs to be done
   0.5 - completed for 00z - memory error towards end of creating zarr stores 
   1 - completed

- NAM
Different sectors to look at
   North America has been done
   CONUS needs to be done
   Alaska needs to be done
Different resolutions
   32km has been completed - memory error towards end of creating zarr stores
   12km needs to be done
   11.25km Relates to sectors

- RAP
Different sectors
   North America
Different resolutions
   32 km

- HRRR
   Needs to be done (ingest process exists)

- Gridded LAMP
   Needs to be done
   https://nomads.ncep.noaa.gov/pub/data/nccf/com/glmp/prod/glmp.20200317/

- SREF
   These are ensemble forecasts, come to later

- RTMA
Sectors
   CONUS
   Guam
   Hawaii
   Puerto Rico

After looking at nomads, in house models, then we can pivot to the other international met services.

**Comment by ShaneMill1** [comment]
One thing that has been happening with the aggregation of the creation of collections, when the zarr datastores are being produced, often there isn't enough memory to process the higher resolution and more complex collections (x,y,z,t).

This has happened so far with:

- gfs 0.50 degree

- gfs 0.25 degree

- nam 32km

May need to look into how to process better when using xarray ds.to_zarr. Also, can look at increasing memory on our VM 

May be useful to log the memory being used so that we can formulate a memory estimate

Suggestion from Mark B:
"You might be able to resolve your xarray issues by changing you chunking size of your xarray datasets"

**Comment by chris-little** [comment]
@ShaneMill1 I suppose one design could be to have details of the individual collections (arrays) and then preprocess the query into separate queries for each ndividual collection. That seems hard at present.

**Comment by ShaneMill1** [comment]
Non NWS grib datasets we will look at next:
https://github.com/opengeospatial/EDR-API-Sprint/wiki/Possible-sources-of-data

- France on AWS
https://registry.opendata.aws/meteo-france-models/
- Canada
https://weather.gc.ca/grib/index_e.html

- Dutch
https://data.knmi.nl/datasets?q=grib

**Comment by ShaneMill1** [comment]
Useful links from George P regarding zarr and pangeo
- https://github.com/pangeo-data/pangeo/issues/450
- https://github.com/zarr-developers/zarr-specs/issues/42

**Comment by ShaneMill1** [comment]
> Non NWS grib datasets we will look at next:
> https://github.com/opengeospatial/EDR-API-Sprint/wiki/Possible-sources-of-data
> 
> * France on AWS
>   https://registry.opendata.aws/meteo-france-models/
> * Canada
>   https://weather.gc.ca/grib/index_e.html
> * Dutch
>   https://data.knmi.nl/datasets?q=grib

First non NWS dataset we have investigated is from Meteo France:

- Arpege
https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=130&id_rubrique=51

- request:
“http://dcpc-nwp.meteo.fr/services/PS_GetCache_DCPCPreviNum?token=__5yLVTdr-sGeHoPitnFc7TZ6MhBcJxuSsoZp6y0leVHU__&model=ARPEGE&grid=0.5&package=IP2&time=00H24H&referencetime=2020-03-19T00:00:00Z&format=grib2”

Wget for each package= IP1,IP2,IP3,IP4,SP1,SP2,HP1,HP2
I is for isobaric
S is for surface
H is for height
Concatenated the grib files to put in a form that the automated collections ingest will use.

Conversion to zarr is successful, but some bumps in the road with populating the correct metadata, so continuing to investigate. 

This shows that the aggregation was successful, but the code within the EDR needs modifying to support how meteo france organized the data. Hoping to expose this data soon in our implementation

**Comment by solson-nws** [comment]
So, with this issue, let's lay out some of the assumptions:

1.  Must be grib data (We want to test both internal NWS grib files and grib files from around the country.  Let's nail down Grib first, then move on to netcdf and HDF5 datasets
2.  Data must have a CRS of WGS84.
3.  Would prefer datasets be global, at least initially.

From a best practice perspective, the goal is to test the automated aggregation of collections scripting for:
1.  Uniqueness of collection IDs.  This becomes particularly important when you consider that each model might have 2 or more different available resolutions for the same geographical area (global, CONUS, etc) and regional models with sectors
2.  Promote consistency on forming Collection IDs
3.  Looking to ensure can be universally applied to grib data created from around the world (local tables?

Lessons learned would feed into a best practice document and would lay out the necessary steps to on-ramp with automation scripts.

**Comment by ShaneMill1** [comment]
Meteo France's data is now available for 00z on our public facing implementation here:

https://data-api.mdl.nws.noaa.gov/EDR-API/collections/automated_arpege_050/00z?outputFormat=application%2Fjson

Will continue to check for errors but it is returning data.

**Comment by chris-little** [comment]
@ShaneMill1 Can you confirm from the GRIBthat the French are using a lat-long WGS84 grid? Their NWP models tend to use rotated poles and also stretched lat-long.

**Comment by ShaneMill1** [comment]
@chris-little 
this is what eccodes shows which looks like WGS84 unless I have it wrong:
  
  latitudeOfFirstGridPointInDegrees = 90;
  longitudeOfFirstGridPointInDegrees = 0;
  latitudeOfLastGridPointInDegrees = -90;
  longitudeOfLastGridPointInDegrees = 359.5;
  iDirectionIncrementInDegrees = 0.5;
  jDirectionIncrementInDegrees = 0.5;
  gridtype = regularll;

regularll is for regular lat lon it looks like

**Comment by chris-little** [comment]
@ShaneMill1 It looks good, but what would those parameters be for a rotated stretched grid?

**Comment by ShaneMill1** [comment]
@chris-little Using eccodes, the grib table is:
gridDefinitionTemplateNumber = **0** [Latitude/longitude  (Also called equidistant cylindrical, or Plate Carrée)  (grib2/tables/5/3.1.table) ]

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml

I presume rotated stretched grid would be a template number of 3. That doesn't appear to be the case here.

**Comment by ShaneMill1** [comment]
Outcome from this objective:

- Successfully used aggregation of collection software to ingest GFS 1.0 Degree, 0.50 Degree, 0.25 Degree, NAM 32km and 12km, and Meteo France's Arpege 0.5 Degree data.

- Identified memory problem when creating zarr datastores for higher resolution data.

- Reminded of important assumption that data must be WGS84, therefore NAM data would need to be converted to this crs.

- Future work will be to test other non-national weather service grib data, optimize the code to solve memory issue.
