### ISSUE TITLE
JSON-Schema for /collections/{collectionID}/items

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/EDR-API-Sprint#15]
The "Items" endpoint here: https://m-burgoyne.github.io/edr_optional_instance_api.html currently uses coverageJSON. I think it should be a GeoJSON Feature Collection with valid query parameters for each item in the collection. 

@jkreft-usgs and I just discussed this and it's in line with what @cportele mentioned in #12 

The trick is how to expose lists of available parameters in geoJSON? Can someone flesh this idea out and think through what other issues might be? I'll be out of pocket till 2ET but will check back then.

**Comment by chris-little** [comment]
CoverageJSON makes sense for multidimensional arrays of data (nD, n>1), so GeoJSON for returning list of Items seems reasonable to me.
What does @m-burgoyne  think?

**Comment by cportele** [comment]
I had a look at the CovJSON spec and how we would implement support for it in ldproxy. I was wondering one thing: How well can it be streamed? Or was that no design consideration and CovJSON documents are always meant to be small?

**Comment by m-burgoyne** [comment]
The candidate specification allows the publisher to advertise the output formats that they support, each of the EDR API querys allows the user to specify which of the output formats they want so both output formats (and others i.e. GeoPackage or Shape) could be supported if the publisher is prepared to inplement the logic in the collection.  

CoverageJSON has a well defined by flexiable schema capable of defining data property meanings and different projections so is much better suited for mashing data between different data domains, the GeoJSON schema only defines location (and then only in EPSG:4326).  It is well supported but provides no information to a user from another domain about the meaning of the data values in the properties section.

**Comment by m-burgoyne** [comment]
@cportele I don't think there is any support for streaming, but it does have the concept of tiling NDimensional data https://covjson.org/spec/#tiledndarray-objects

**Comment by cportele** [comment]
@m-burgoyne - Thanks for the clarification. So since tiling will only really work for results that can be cached and you are returning CovJSON that is created on-the-fly in your prototype (I think), is my conclusion correct that CovJSON is only meant for smallish payloads? I am asking, because I was expecting that EDR API responses could also sometimes become "big" (mega bytes).

**Comment by m-burgoyne** [comment]
@cportele, yes CoverageJSON should only be for small payloads (as is true of any text based format).  The EDR candidate specification does allow the publisher to advertise other output formats and has a specific HTTP error code to inform the user their request will payload is too large too process.   One of the aims of the EDR format is to encourage users to ask for just the data they need, although the Cube (and many Polygon queries) will often not be able to use CoverageJSON due to size limitations.  The candidate specification also has an approach to asynchronous so there is also a mechanism to tell the user they will need to wait while the tiles are generated.

**Comment by chris-little** [comment]
@cportele And the definition of 'small' for CoverageJSON is that it can be downloaded into a browser for local, client-side, processing, such as innovative visualisation.

**Comment by cportele** [comment]
@chris-little - Also in the use case streaming is useful for the user experience.

**Comment by chris-little** [comment]
@cportele - well not really. Streaming usually implies some chunks, such as images or sound bites, can be dropped and only the latest in the stream matters. In general, this is not true for a lot of environmental data - it has to be lossless and complete, otherwise the science is screwed.

**Comment by dblodgett-usgs** [comment]
I think the streaming @cportele is referring to is in the sense of a database query -- Can the format be streamed out before the query has completely returned such that the client-server connection can open nearly synchronously? Or does the format require complete serialization on the server before starting the stream? e.g. xml with metadata a la TimeseriesML vs a zipped package.

**Comment by cportele** [comment]
@dblodgett-usgs - exactly, thanks.

@chris-little - I think most implementations of OGC API Features use streaming when they return features, typically a feature per chunk. Streaming is not just video, etc. That way the client can start to do something with the incoming features, before the query on the server is finished. This is not really important when you request ten features, but that changes if you request a few thousand or more.

**Comment by m-burgoyne** [comment]
In theory you could use the https://covjson.org/spec/#tiledndarray-objects approach to achieve a similar result.

**Comment by cportele** [comment]
@m-burgoyne - But that would require that the tiles could be all in the same document/response/JSON object, which currently doesn't seem to be the case?

**Comment by m-burgoyne** [comment]
@cportele, yes it would require client side logic as the parent document has to be loaded to identify the availble tiles (each of which is a seperate document).

**Comment by dblodgett-usgs** [comment]
Learning some of the tech on the job here -- so bear with me. 

I'm thinking something along the lines of this:

```json
{
  "type": "FeatureCollection",
  "crs": {
    "type": "EPSG",
    "properties": {
      "code": 4326,
      "coordinate_order": [ 1, 0 ]
    }
  },
  "features": [
    {
      "type": "Feature",
      "id": "123",
      "geometry": {
        "type": "Point",
        "coordinates": [ -105.683442, 36.740017 ]
      },
      "properties": {
        "datetime": "2018-02-12T00:00:00Z/2018-03-18T12:31:12Z",
        "parametername": [ "param object 1", "param object 2" ],
        "label": "Something like a site name to use on a link",
        "uri": "https://feature_identifier"
      }
    }
  ]
}
```
This validates against the geojson schema anyways.

- `id` is what goes in `/collection/{collectionID}/items/{itemID}`. (I ripped this from OGC-API Features Example 12)
- `datetime` follows features.
- `parametername` follows the draft spec naming convention. (Does geojson really support arrays in the properties?!?)
- `label` because you have to have a list/link label in your app.
- `uri` which I was going to make `@id` to allude to json-ld and the idea that it should really be a linked data feature ID that 303 redirects if this is a real-world sampling feature. 

I'm not versed enough to sneak these extensions in to the geojson FeatureCollection schema. Maybe someone else can tackle that if this is a reasonable approach here?

Cool! `R` `sf` which wraps `gdal` says: (woot woot to even getting the datetime right and parameters as a list!!)
```r
> sf::read_sf("~/Documents/active_code/EDR-API-Sprint/items/test.geojson")
Simple feature collection with 1 feature and 5 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -105.6834 ymin: 36.74002 xmax: -105.6834 ymax: 36.74002
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
# A tibble: 1 x 6
  id    datetime            label                uri           parametername                geometry
  <chr> <dttm>              <chr>                <chr>         <list>                    <POINT [°]>
1 123   2018-02-11 18:00:00 Something like a si… https://feat… <chr [2]>        (-105.6834 36.74002)
```

**Comment by chris-little** [comment]
Streaming: can we say that the first version of EDR API will not do streaming? 
Does this then imply that the Tile pattern repsonse is one tile, not lots? Requesting an extensive bounding box and hoping to get lots of tiles rather goes against the orignal scope and use cases.

**Comment by m-burgoyne** [comment]
No, the Tile pattern is still suitable for situations where you have large volumes of data that for some reason you want to deliver as CoverageJSON

**Comment by cportele** [comment]
> Streaming: can we say that the first version of EDR API will not do streaming?

I wouldn't say that in the spec. 

In general it is a decision of an implementation, if it uses streaming or not. No implementation is required to support streaming.

In addition, it will depend on the encoding. If the EDR API returns a media type that can be streamed the such a statement would be wrong, too. 

And looking at the draft spec, it lists a GeoJSON conformance class. It is not really clear to me how GeoJSON is returned where after a quick search, but where it is used, streaming is possible.

**Comment by dblodgett-usgs** [comment]
Do you guys want to open an issue for streaming and EDR content types? This issue wasn't really supposed to be about that.

**Comment by chris-little** [comment]
I think we have closed off the streaming issue. It would be nice to copy it into its own thread for newbies to follow.

**Comment by cportele** [comment]
@dblodgett-usgs - Yes, sorry for the digression. I have copied all streaming related discussion to #18. It could be removed here, but this is nothing I can do with my rights in this repo.

**Comment by dblodgett-usgs** [comment]
This issue was split into two due to a split in the discussion -- probably would have been easy to start a new one for the original purpose and rename this one. 🤷‍♂️

**Comment by dblodgett-usgs** [comment]
@jkreft-usgs ... 

The properties schema is [here](https://github.com/jkreft-usgs/edr_site_based/blob/9b0b3baa923bd7314d5a47fc84aa58e41ef23043/schemas/EDR_items.yaml#L1628), also here:

```
properties:
      type: object
      title: The Properties Schema
      description: An explanation about the purpose of this instance.
      default: {}
      example:
      -   datetime: 2018-02-12T00:00:00Z/2018-03-18T12:31:12Z
          label: Something like a site name to use on a link
          parametername:
          - param object 1
          - param object 2
          uri: https://feature_identifier
      required:
        - datetime
        - parametername
        - label
        - uri
      properties:
        datetime:
            type: string
            title: The Datetime Schema
            description: An explanation about the purpose of this instance.
            default: ''
            example:
            - 2018-02-12T00:00:00Z/2018-03-18T12:31:12Z
        parametername:
            type: array
            title: The Parametername Schema
            description: An explanation about the purpose of this instance.
            default: []
            items:
                type: string
                title: The Items Schema
                description: An explanation about the purpose of this instance.
                default: ''
                example:
                - param object 1
                - param object 2
        label:
            type: string
            title: The Label Schema
            description: An explanation about the purpose of this instance.
            default: ''
            example:
            - Something like a site name to use on a link
        uri:
            type: string
            title: The Uri Schema
            description: An explanation about the purpose of this instance.
            default: ''
            example:
            - https://feature_identifier
```

**Comment by dblodgett-usgs** [comment]
Cool -- We'll need to clean that up, but by my understanding the actual meat of the thing starts [here.](https://github.com/jkreft-usgs/edr_site_based/blob/9b0b3baa923bd7314d5a47fc84aa58e41ef23043/schemas/EDR_items.yaml#L1403) I'll putter on this a bit and get a PR sent your way this morning @jkreft-usgs.

**Comment by dblodgett-usgs** [comment]
https://github.com/jkreft-usgs/edr_site_based/pull/1/files
