### ISSUE TITLE
Objective: Conformance testing

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#16]
As Stephan Siemen from ECMWF said, some form of testing needs to be done, in particular, for the returned data payload:
- GeoJSON has a clear standard to test against.
- CoverageJSON is well defined by the original work done by Jon Blower and Maik Reichardt at Reading University, but we have also started, rather slowly, the process to agree an OGC standard for the structure of CoverageJSON. See the repo at https://github.com/opengeospatial/CoverageJSON. 
- OGC API Features has a conformance test suite, and presumably, some of this will be shared with an OGC API Common test suite.

There is then the need for the content of the payload from a specific query to be tested for conformance.

**Comment by cmheazel** [comment]
We have a conformance test for API-Features.  This test was written to be modular.  So we should be able to create a set of conformance test modules to match our API modules.  Now we just need to see if it actually works as planned.

**Comment by cmheazel** [comment]
Conformance tests for the returned payload is a bit harder.  With XML we had a validating XML schema and Schematron rules.  While there is a JSON schema standard, it is nowhere near as rigorous as XML schema.  At this point I'm not sure that tools exist to do serious JSON validation.  Much less the other formats which we can expect to see.

**Comment by chris-little** [comment]
This is now a continuing issue [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
