### ISSUE TITLE
ESRI sprint telco

### ISSUE THREAD

**Issue by PeterTrevelyan** [opengeospatial/EDR-API-Sprint#17]
**### **Meetint to be held at 14:00 BST (UK) note we are only 7 hours ahead of Pacific time****

Join Skype Meeting      
Trouble Joining? Try Skype Web App
Join by phone

+1 855-630-7113 (North America),,9411250# (North America)                                 English (United States) 
+1 909 369-3165 (US Local),,9411250# (North America)                            English (United States)  

Find a local number 

Conference ID: 9411250
Forgot your dial-in PIN? |Help   
Join Skype Meeting      
Trouble Joining? Try Skype Web App
Join by phone

+1 855-630-7113 (North America),,9411250# (North America)                                 English (United States) 
+1 909 369-3165 (US Local),,9411250# (North America)                            English (United States)  

Find a local number 

Conference ID: 9411250
Forgot your dial-in PIN? |Help

**Comment by chris-little** [comment]
@PeterTrevelyan My understanding is that ESRI and you are looking to demonstrate EDR API, for points/timeseries/vertical profiles, and cube/tiles, retrieving from ESRI Image Server or similar product?

**Comment by chris-little** [comment]
Implementation experimentation is continuing outside of Sprint and EDR API SWG.
