### ISSUE TITLE
Explore putting EDR API on ESRI REST API image server

### ISSUE THREAD

**Issue by PeterTrevelyan** [opengeospatial/EDR-API-Sprint#2]

**Comment by chris-little** [comment]
@PeterTrevelyan can you add a bit more detail please. And which EDR API patterns do you envisage? Point, Timeseries, Profile, Polygon, Tile, Trajectory/Corridor?

**Comment by PeterTrevelyan** [comment]
The main aim of this work is to show how  the EDR "Pattern" may be "mapped"  onto a proprietary REST API , such as ESRI's Arc Image Server. The output from this  work will be a document outlining the issues that are brought to light and a very simple prototype consisting of a simple proxy server that uses the EDR API and translates into the Image Server REST API
