### ISSUE TITLE
Objective: Mark Burgoyne developing new EDR API server and client

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#20]
@m-burgoyne Perhaps you could put in a bit nore detail for our edification, and the final report.

**Comment by m-burgoyne** [comment]
Build a simple EDR server to demonstrating Point, Polygon and Items queries against the same collection.  It will also demonstrate an alternative approach to **item_id**.  With the proposed application **item_id** is a unique identifier for a location (i.e. a METAR id, GeoHash key, What Three Words etc) which has a set of data assigned to it.

**Comment by chris-little** [comment]
Use of named locations agreed. Future work on [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
