### ISSUE TITLE
WHU sprint goals

### ISSUE THREAD

**Issue by boyi-shangguan** [opengeospatial/EDR-API-Sprint#3]
## Narrative
WHU plans to provide the implementation of EDR API service. We will initially focus on the typhoon use cases, including using EDR API to access typhoon tracking data and using them as filters to retrieve the rainfall data or other environmental data, further creating downstream applications and services in favor of both public and private sector stakeholders (e.g., National Marine Environmental Forecasting Center (NMEFC)). 
Here are some sample cases:
- Case 1: Get all typhoon cases during a typhoon season from the typhoon collection "hainan_typhoon": /collections/hainan_typhoon/items?time=2019-06-01T00:00:00Z/2019-09-30T00:00:00Z&bbox=108.8,19.0,109.3,19.4
- Case 2: Get the typhoon tracking data, assuming a specific typhoon case is named "dianmu": /collections/hainan_typhoon/items/dianmu
- Case 3: Get the rainfall data during the specific typhoon from the weather collection "hainan_weather": /collections/hainan_weather/corridor?parametername=rainfall&coords=LINESTRING(-3.45 50.78 ,-3.45 50.78,-3.46 50.78,-3.46 50.77,-3.46 50.76, -3.46 50.75)&time=2019-06-01T00:00:00Z/2019-09-30T00:00:00Z
## Questions
- What would typhoon metadata look like as a collection of EDR items?
- In Case 3, is it possible to define named feature "dianmu" as a filter directly instead of using both the coords and time?
- Considering the responses, is it a user-defined behavior to return either GeoJSON or Coverage for Case 3?
## Goals
- Provide a typhoon use case that supports the combination of environmental data retrieval
- Provide a demonstration implementation for the EDR API with WHU use-cases.
- Provide typhoon data service using EDR APIs.
## Participants
- Peng Yue (@geopyue)
- Boyi Shangguan  (@sgby)
- Lei Hu
- Mingda Zhang (@zhangmingda)

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne 👍  WHU's Case 3 looks as if it is the same as the Items issue.

**Comment by dblodgett-usgs** [comment]
Yes -- I think it is.

**Comment by boyi-shangguan** [comment]
We discussed to use **LINESTRING(...)**, **LINESTRINGZ(...)**, **LINESTRINGM(...)**, **LINESTRINGMZ(...)** in **_coords_** to distinguish trajectory query pattern, for example:

+ A 2D trajectory, on the surface of earth, at the same time:
**_coords_=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)**

+ A 3D trajectory, on the surface of the earth but over a time range:
**_coords_=LINESTRINGM(51.14 -2.98 1560507000, 51.36 -2.87 1560507600, 51.03 -3.15 1560508200, 50.74 -3.48 1560508500, 50.9 -3.36 1560510240)**

+ A 3D trajectory, through a 3D volume with height or depth, for the same time:
**_coords_=LINESTRINGZ(51.14 -2.98 0.1, 51.36 -2.87 0.2, 51.03 -3.15 0.3, 50.74 -3.48 0.4, 50.9 -3.36 0.5)**

+ A 4D trajectory, through a 3D volume but over a time range:
**_coords_=LINESTRINGZM(51.14 -2.98 0.1 1560507000,51.36 -2.87 0.2 1560507600, 51.03 -3.15 0.3 1560508200, 50.74 -3.48 0.4 1560508500, 50.9 -3.36 0.5 1560510240)**

An example for querying rainfall data with a 3D (t, x, y) typhoon trajectory:

+ Request:
````
http://geos.whu.edu.cn/edr/collections/hainan_weather/trajectory?parametername=rainfall&coords=LINESTRINGM(112.7 21.1 1471392000, 112.5 20.9 1471402800, 112.6 20.5 1471413600, 112.7 20.6 1471424400, 112.7 20.7 1471435200)
````
+ Response:
````
{
    "type": "Coverage",
    "domain": {
        "type": "Domain",
        "domainType": "Trajectory",
        "composite": {
            "dataType": "tuple",
            "coordinates": ["t", "x", "y"],
            "values": [ ["2016-08-17T08:00:00Z", 112.7, 21.1], ["2016-08-17T11:00:00Z", 112.5, 20.9], ["2016-08-17T14:00:00Z", 112.6, 20.5], ["2016-08-17T17:00:00Z", 112.7, 20.6],["2016-08-17T20:00:00Z", 112.7, 20.7]]
        }
    },
    "parameters": {
        "rainfall": {
            "type": "Parameter",
            "id": "rainfall",
            "description": {
                "en": "Rainfall value"
            },
            "unit": {
                "label": {
                    "en": "Mmmillimetre"
                },
                "symbol": {
                    "value": "mm"
                }
            },
            "observedProperty": {
                "id": "http://vocab.nerc.ac.uk/standard_name/rainfall/",
                "label": {
                    "en": "Rainfall"
                }
            }
        }
    },
    "ranges": {
        "rainfall": {
            "type": "NdArray",
            "dataType": "float",
            "axisNames": ["composite"],
            "shape": [5],
            "values": [12.2, 12, 13.3, 11.2, 8.7]
        }
    }
}
````

**Comment by m-burgoyne** [comment]
That does make a lot of sense, I had missed that part of the simple features specification and it would also make the documentation a lot clearer for people to understand. The same will apply to the other N-Dimensional queries

**Comment by boyi-shangguan** [comment]
A simple web service endpoint demo is provided for trajectory query:
[114.116.247.114:8080/edr/collections/hainan_weather/trajectory](url)

At present, we just realize query with (x,y,t) trajectory, like:
[114.116.247.114:8080/edr/collections/hainan_weather/trajectory?parametername=rainfall&coords=LINESTRINGM(112.7 21.1 1471392000, 112.5 20.9 1471402800, 112.6 20.5 1471413600, 112.7 20.6 1471424400, 112.7 20.7 1471435200)](url)

Next step will focus on a live demo for the query.

**Comment by chris-little** [comment]
The Objectives were achieved in the Sprint.
Sprint now closed.
Further issues and objectives will now be followed on [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
