### ISSUE TITLE
Objective: Point, timeseries at a point ,and vertical profile at a point

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#4]
Data to be retrieved from various datastores for position (x, y, z, t), or (x, y, z, t1-t2), or (x, y, z1-z2, t)

May need to discuss whether position (x, y, z1-z2, t1-t2) is currently in scope. I.e. is more than one range allowed in the position?

**Comment by chris-little** [comment]
@m-burgoyne Is it feasible to extract data over two ranges? Or shall we defer this to a later stage? Can we do the vertical profile now?

**Comment by m-burgoyne** [comment]
@chris-little I think the trajectory query would solve this requirement, it can be made up of an array of 4D points [(x1,y1,z1,t1),(x1,y1,z2,t2),(x1,y1,z3,t3) ...]

**Comment by chris-little** [comment]
@m-burgoyne but can we do timeseries and/or vertical profile? These are not the same as a 4D trajectory. Or have I misunderstood something?

**Comment by m-burgoyne** [comment]
@chris-little I think it would be useful to have actual example use cases to map the question to.  In some cases it might just be simpler to make multiple simple requests to an API rather than trying to create a query with too many dimensions.  As in your original example some of the inputs to the query were not actually array values but min and max ranges, but you were trying to specifiy them in the same way as the other coordinates which were array values.

**Comment by chris-little** [comment]
Is a point location (x, y, z1-z2, t1-t2) in scope? I.e. is more than one range allowed in the position?
Use Case: construct a Hovmöller diagram of a parameter like potential temperature at a location (x,y). This is a vertical (z,t) graph/diagram with the horizontal x axis being Time, and the vertical y axis Altitude. The EDR API calls could be either:
1. (x, y, zi, t1-t2) called several times for multiple levels, or
2. (x, y, z1-z2, ti) called several times for multiple times, or
3 (x, y, z1-z2, t1-t2) once.

I think (1) and (2) are good enough and not too much burden on the user.

I  do not think there is much distinction between specifying (min, max) and array values. This is quite standard in, say, regular expressions.

**Comment by m-burgoyne** [comment]
The candidate specification has time as a seperate range parameter for the point query which covers (1) and I think that the trajectory query should cover (2) and (3)

**Comment by chris-little** [comment]
This issue has been discussed and transferred to the [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
A very useful debate.
