### ISSUE TITLE
Objective: polygon in 3D or 4D

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#6]
1. Retrieve from various datastores data that extend vertically above or below the polygon. I.e. there is a vertical range (z1-z2) specified.

2. Retrieve from various datastores data that extend in time within the polygon. I.e. there is a time range (t1-t2) specified, which may be in the future or the past.

3. Do we allow a 4D polygon extended vertically and in time?

It is assumed that there will be no polyhedra or polytopes (complex multidimensional polygons), rather than just 'extruded' 2D polygons. An extruded 2D polygon can be called a 'prism'.

**Comment by chris-little** [comment]
@m-burgoyne I assume the answer to (3) is the same as in Issue #4, do we allow two ranges or just one for the time being?

**Comment by m-burgoyne** [comment]
@chris-little #3 is the Cube query

**Comment by chris-little** [comment]
@m-burgoyne So the Cube query encompasses a non-rectangular polygon, extruded with time and elevation ranges?

**Comment by chris-little** [comment]
Current consensus is that 2+D queries allow a 2D area to be extended in Time or extended vertically, but not both at the same time. 
It should not be too difficult to do both at the same time as the CoverageJSON could handle it, but the payload starts being not small and convenient. Future work to enhance the standard.
