### ISSUE TITLE
Objective: Tile/Cube in 3D or 4D

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#8]
Retrieve data from various data stores where the specified polygon is a rectangle, extended vertically or in time.

Is a compact notation of ranges for each dimension allowed? I.e. ( (x1-x2), (y1-y2), (z1-z2), (t1-t2) ) or similar such as ( (x1, y1, z1, t1), (x2, y2, z2, t2) ) ?

**Comment by chris-little** [comment]
Ranges in each dimension gives some consistency with the Timeseries and Vertical Profile pattern queries.
Specifying the diagonal corners gives consistency with the special case of a rectangular polygon.
@m-burgoyne My preference is for the former pattern - specifying ranges for each dimension for consistency with Timeseries and Vertical Proifle

**Comment by m-burgoyne** [comment]
@chris-little in the Cube API I specified that is was a 2D WKT Polygon with seperate time range and Z query parameters. This forces the height and time values to be ranges rather than a random collection of values.

**Comment by cmheazel** [comment]
Would it be out of scope to propose extensions to the WKT geometry?  An n-dimensional WKT?

**Comment by m-burgoyne** [comment]
I think WKT is capable of specifying enough dimensions for this query,  the solution was more about constraining the query parameters to a range of inputs that are valid.

**Comment by chris-little** [comment]
@cmheazel Yes - out of scope, until we encounter something that we cannot represent in current WKT.

**Comment by chris-little** [comment]
More implementation experience needed beofre extending the query scope
