### ISSUE TITLE
Objective: Trajectory, 2D, 3D or 4D

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/EDR-API-Sprint#9]
Retrieve data from various data stores along a specified trajectory.

A 2D trajectory, on the surface of earth, at the same time. ( (x1,y1), (x2,y2), ...(xn,yn) )

A 3D trajectory, on the surface of the earth but over a time range. ( (x1,y1,t1), (x2,y2,t2), ...(xn,yn,tn) )

A 3D trajectory, through a 3D volume with height or depth, for the same time  
( (x1,y1,z1), (x2,y2,z2), ...(xn,yn,zn) )

A 4D trajectory, through  a 3D volume but over a time range 
( (x1,y1,z1,t1), (x2,y2,z2,t2), ...(xn,yn,zn,tn) )

**Comment by boyi-shangguan** [comment]
Notice that we have query patterns of '**_point_**', **'_polygon_**' but without '**_linestring_**'. For trajectory can be regarded as a special kind of linestring, is it better to rename the query pattern '**_trajectory_'** to '**_linestring_**' ？

**Comment by m-burgoyne** [comment]
I think **'point'** and **'polygon'** are fairly common terms **'linestring'** isn't as user friendly.  **'trajectory'** is slightly more meaningful

**Comment by chris-little** [comment]
@sgby I agree with @m-burgoyne . "Linestring" is a specific jargon for geospatial or computer graphics specialists. "Trajectory" is the correct English word in every dictionary. Linestring is the technical implementation of the trajectory concept.

**Comment by cportele** [comment]
If there is a preference for 'trajectory' over 'linestring', shouldn't it be 'location' instead of 'point' and 'area' instead of 'polygon'?

**Comment by m-burgoyne** [comment]
@cportele I agree

**Comment by chris-little** [comment]
I agree for 'Area'. Orginally, I think we chose the words that we did to emphasise the topological and dimensional differences of the queries.

The problem with 'Location' is that it is construed usually as 2D, rather than 4D. 'Position' may be better. 'Point' would be applicable to a 4+D space, e.g. with frequency as a dimension, or ensmble member.

**Comment by chris-little** [comment]
Issues resolved and renames transferred to [Environmental Data Retrieval API repo](https://github.com/opengeospatial/Environmental-Data-Retrieval-API)
